version: "3.7"

services:
  analytics-api:
    build:
      context: .
    image: frishi/analytics-service-api
    container_name: analytics-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    external_links: 
      - nats
      - zookeeper
    labels:
      - traefik.http.services.analytics-api.loadbalancer.server.port=3000
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.routers.analytics-api.service=analytics-api@docker
      - traefik.http.routers.analytics-api.rule=Host(`localhost`) && PathPrefix(`/api/analytics/`)
    networks:
      - gateway

  analytics-service:
    build:
      context: .
    image: frishi/analytics-service
    container_name: analytics-service
    env_file: docker-compose.env
    environment:
      SERVICES: analytics
    labels:
      - traefik.enable=false
    external_links: 
      - nats
      - zookeeper
    networks:
      - gateway

networks:
  gateway:
    external: true
