version: "3.3"

services:
  analytics-api:
    build:
      context: .
    image: frishi/analytics-service-api
    container_name: analytics-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 9876
    external_links: 
      - nats
      - caddy
    networks:
      - main-network 

  analytics-service:
    build:
      context: .
    image: frishi/analytics-service
    container_name: analytics-service
    env_file: docker-compose.env
    environment:
      SERVICES: analytics
    external_links: 
      - nats
      - zookeeper
      - caddy
    networks:
      - main-network

networks:
  main-network:
    external: true
